// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/math/v1/math.proto

#include "proto/math/v1/math.pb.h"
#include "proto/math/v1/math.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace proto {
namespace math {
namespace v1 {

static const char* MathService_method_names[] = {
  "/proto.math.v1.MathService/Add",
};

std::unique_ptr< MathService::Stub> MathService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MathService::Stub> stub(new MathService::Stub(channel, options));
  return stub;
}

MathService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Add_(MathService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MathService::Stub::Add(::grpc::ClientContext* context, const ::proto::math::v1::AddRequest& request, ::proto::math::v1::AddResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::proto::math::v1::AddRequest, ::proto::math::v1::AddResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Add_, context, request, response);
}

void MathService::Stub::async::Add(::grpc::ClientContext* context, const ::proto::math::v1::AddRequest* request, ::proto::math::v1::AddResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::proto::math::v1::AddRequest, ::proto::math::v1::AddResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Add_, context, request, response, std::move(f));
}

void MathService::Stub::async::Add(::grpc::ClientContext* context, const ::proto::math::v1::AddRequest* request, ::proto::math::v1::AddResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Add_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::proto::math::v1::AddResponse>* MathService::Stub::PrepareAsyncAddRaw(::grpc::ClientContext* context, const ::proto::math::v1::AddRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::proto::math::v1::AddResponse, ::proto::math::v1::AddRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Add_, context, request);
}

::grpc::ClientAsyncResponseReader< ::proto::math::v1::AddResponse>* MathService::Stub::AsyncAddRaw(::grpc::ClientContext* context, const ::proto::math::v1::AddRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddRaw(context, request, cq);
  result->StartCall();
  return result;
}

MathService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MathService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MathService::Service, ::proto::math::v1::AddRequest, ::proto::math::v1::AddResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MathService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::proto::math::v1::AddRequest* req,
             ::proto::math::v1::AddResponse* resp) {
               return service->Add(ctx, req, resp);
             }, this)));
}

MathService::Service::~Service() {
}

::grpc::Status MathService::Service::Add(::grpc::ServerContext* context, const ::proto::math::v1::AddRequest* request, ::proto::math::v1::AddResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace proto
}  // namespace math
}  // namespace v1

